// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Greet(arg1: string): Promise<string>;

export function ListFileInfo(arg1: string): Promise<Array<model.FileInfo>>;

export function OpenFileDialog(): Promise<Array<model.TreeNode>>;
